# Generated by Django 5.0.2 on 2025-04-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
